2. Generate at random 3 matrices of size $3 \times 3$ and fill each entry with a random integer chosen from -10 to 10. Use an existing package to compute the inverse of each matrix if it exists. Include in your report:
    - Each of the 3 matrices
    - The inverses computed with the package
    - Compute the product of each matrix with its inverse to check that you obtain the identity matrix.


In [2]:
import numpy as np

matrix1 = np.random.randint(-10, 11, size=(3,3))
matrix2 = np.random.randint(-10, 11, size=(3,3))
matrix3 = np.random.randint(-10, 11, size=(3,3))

print("Matrix 1:\n", matrix1)
print("\nMatrix 2:\n", matrix2)
print("\nMatrix 3:\n", matrix3)


Matrix 1:
 [[ 5  9  8]
 [ 0  8 -1]
 [ 0 -5  1]]

Matrix 2:
 [[ 9 -7  3]
 [-5  9 -5]
 [ 4 -7  5]]

Matrix 3:
 [[ 6 -8 -7]
 [10 -2  2]
 [ 6 -7  1]]


In [3]:
inverse_1 = np.linalg.inv(matrix1)
inverse_2 = np.linalg.inv(matrix2)
inverse_3 = np.linalg.inv(matrix3)

print("Inverse of Matrix 1\n", inverse_1)
print("\nInverse of Matrix 2\n", inverse_2)
print("\nInverse of Matrix 3\n", inverse_3)


Inverse of Matrix 1
 [[ 0.2        -3.26666667 -4.86666667]
 [ 0.          0.33333333  0.33333333]
 [ 0.          1.66666667  2.66666667]]

Inverse of Matrix 2
 [[ 0.19230769  0.26923077  0.15384615]
 [ 0.09615385  0.63461538  0.57692308]
 [-0.01923077  0.67307692  0.88461538]]

Inverse of Matrix 3
 [[ 0.02597403  0.12337662 -0.06493506]
 [ 0.004329    0.1038961  -0.17748918]
 [-0.12554113 -0.01298701  0.14718615]]


In [4]:
product_m1_i1 = matrix1 @ inverse_1

product_m2_i2 = matrix2 @ inverse_2

product_m3_i3 = matrix3 @ inverse_3

def clean_matrix(matrix):
    matrix_rounded = np.round(matrix, 6)
    matrix_rounded_bool = np.abs(matrix_rounded) < 1e-10 
    matrix_rounded[matrix_rounded_bool] = 0
    return matrix_rounded


print("Product of Matrix 1 and its Inverse:\n", clean_matrix(product_m1_i1))
print("\nProduct of Matrix 2 and its Inverse:\n", clean_matrix(product_m2_i2))
print("\nProduct of Matrix 3 and its Inverse:\n", clean_matrix(product_m3_i3))

Product of Matrix 1 and its Inverse:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Product of Matrix 2 and its Inverse:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Product of Matrix 3 and its Inverse:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
